command_timeout = 1000


[aws]
style = "bold blue"
symbol = "ğŸ…° "

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "symbol" segment is being set to "âœ"
error_symbol = "[âœ](bold red)"     # The "symbol" segment is being set to "âœ"

[cmd_duration]
min_time = 2

[directory]
truncation_length = 8

[git_status]
disabled = true

[rust]
symbol = "Rust "

[time]
disabled = false
time_format = "[ %T ]"
utc_time_offset = -5


